# Generated by Django 5.2.4 on 2025-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("client", "Cliente"), ("admin", "Administrador")],
                default="client",
                max_length=10,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
