# Generated by Django 5.2.3 on 2025-07-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pergunta",
                    models.CharField(
                        help_text="A pergunta frequente",
                        max_length=500,
                        verbose_name="Pergunta",
                    ),
                ),
                (
                    "resposta",
                    models.TextField(
                        help_text="A resposta detalhada para a pergunta",
                        verbose_name="Resposta",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Se esta FAQ está visível no site",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição (menor número aparece primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["ordem", "criado_em"],
            },
        ),
    ]
