# Generated by Django 5.2.4 on 2025-07-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("prestacao_servico", "Prestação de Serviço"),
                            ("locacao_residencial", "Locação Residencial"),
                            ("locacao_comercial", "Locação Comercial"),
                            ("compra_venda", "Compra e Venda"),
                            ("confissao_divida", "Confissão de Dívida"),
                            ("freelancer", "Freelancer"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contract_types/",
                        verbose_name="Imagem",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contratos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("paid", "Pago"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/",
                        verbose_name="Arquivo PDF",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "parte1_nome",
                    models.CharField(max_length=200, verbose_name="Nome da Parte 1"),
                ),
                (
                    "parte1_cpf_cnpj",
                    models.CharField(max_length=18, verbose_name="CPF/CNPJ da Parte 1"),
                ),
                (
                    "parte1_endereco",
                    models.TextField(verbose_name="Endereço da Parte 1"),
                ),
                (
                    "parte2_nome",
                    models.CharField(max_length=200, verbose_name="Nome da Parte 2"),
                ),
                (
                    "parte2_cpf_cnpj",
                    models.CharField(max_length=18, verbose_name="CPF/CNPJ da Parte 2"),
                ),
                (
                    "parte2_endereco",
                    models.TextField(verbose_name="Endereço da Parte 2"),
                ),
                (
                    "objeto_contrato",
                    models.TextField(verbose_name="Objeto do Contrato"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(max_length=200, verbose_name="Forma de Pagamento"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "prazo_vigencia",
                    models.CharField(max_length=100, verbose_name="Prazo de Vigência"),
                ),
                (
                    "dados_especificos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Específicos"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracttype",
                        verbose_name="Tipo de Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("approved", "Aprovado"),
                            ("cancelled", "Cancelado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Cartão de Crédito"),
                            ("debit_card", "Cartão de Débito"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID da Transação",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-created_at"],
            },
        ),
    ]
