# Generated by Django 5.2.4 on 2025-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttype",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="Categoria"),
        ),
        migrations.AddField(
            model_name="contracttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="Slug"
            ),
        ),
    ]
