# Generated by Django 5.2.4 on 2025-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contracttype_category_contracttype_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contracttype",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contratos",
            },
        ),
        migrations.AddField(
            model_name="contracttype",
            name="color",
            field=models.CharField(
                default="#f4623a",
                help_text="Cor em hexadecimal (ex: #f4623a)",
                max_length=7,
                verbose_name="Cor",
            ),
        ),
        migrations.AddField(
            model_name="contracttype",
            name="icon",
            field=models.CharField(
                default="fas fa-file-contract",
                help_text="Ex: fas fa-file-contract, fas fa-building",
                max_length=50,
                verbose_name="Ícone FontAwesome",
            ),
        ),
        migrations.AddField(
            model_name="contracttype",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Menor número aparece primeiro",
                verbose_name="Ordem de Exibição",
            ),
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
    ]
