# Generated by Django 5.2.3 on 2025-07-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_compravendaimovel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoCompraVendaImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proprietario_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo do Proprietário"
                    ),
                ),
                (
                    "proprietario_estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "proprietario_nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "proprietario_profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("proprietario_rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "proprietario_cpf",
                    models.CharField(max_length=14, verbose_name="CPF"),
                ),
                (
                    "proprietario_endereco_rua",
                    models.CharField(max_length=200, verbose_name="Rua"),
                ),
                (
                    "proprietario_endereco_numero",
                    models.CharField(max_length=20, verbose_name="Número"),
                ),
                (
                    "proprietario_endereco_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "proprietario_endereco_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "proprietario_endereco_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "proprietario_endereco_cep",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "proprietario_conjuge_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_nacionalidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nacionalidade do Cônjuge",
                    ),
                ),
                (
                    "proprietario_conjuge_profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_rg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RG do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Cônjuge"
                    ),
                ),
                (
                    "comprador_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo do Comprador"
                    ),
                ),
                (
                    "comprador_estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "comprador_nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "comprador_profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("comprador_rg", models.CharField(max_length=20, verbose_name="RG")),
                ("comprador_cpf", models.CharField(max_length=14, verbose_name="CPF")),
                (
                    "comprador_endereco_rua",
                    models.CharField(max_length=200, verbose_name="Rua"),
                ),
                (
                    "comprador_endereco_numero",
                    models.CharField(max_length=20, verbose_name="Número"),
                ),
                (
                    "comprador_endereco_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "comprador_endereco_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "comprador_endereco_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "comprador_endereco_cep",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "comprador_conjuge_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Cônjuge"
                    ),
                ),
                (
                    "comprador_conjuge_nacionalidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nacionalidade do Cônjuge",
                    ),
                ),
                (
                    "comprador_conjuge_profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão do Cônjuge"
                    ),
                ),
                (
                    "comprador_conjuge_rg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RG do Cônjuge"
                    ),
                ),
                (
                    "comprador_conjuge_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Cônjuge"
                    ),
                ),
                (
                    "imovel_tipo",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("chacara", "Chácara"),
                            ("cobertura", "Cobertura"),
                            ("duplex", "Duplex"),
                            ("fazenda", "Fazenda"),
                            ("flat", "Flat"),
                            ("galpao", "Galpão"),
                            ("kitnet", "Kitnet"),
                            ("loft", "Loft"),
                            ("mansao", "Mansão"),
                            ("sitio", "Sítio"),
                            ("sobrado", "Sobrado"),
                            ("studio", "Studio"),
                            ("terreno", "Terreno"),
                        ],
                        max_length=20,
                        verbose_name="Tipo do Imóvel",
                    ),
                ),
                (
                    "imovel_endereco_rua",
                    models.CharField(max_length=200, verbose_name="Rua"),
                ),
                (
                    "imovel_endereco_numero",
                    models.CharField(max_length=20, verbose_name="Número"),
                ),
                (
                    "imovel_endereco_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "imovel_endereco_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "imovel_endereco_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "imovel_endereco_cep",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "imovel_matricula",
                    models.CharField(max_length=50, verbose_name="Número da Matrícula"),
                ),
                (
                    "imovel_cartorio",
                    models.CharField(
                        max_length=200, verbose_name="Cartório de Registro"
                    ),
                ),
                (
                    "imovel_iptu",
                    models.CharField(max_length=50, verbose_name="Número do IPTU"),
                ),
                (
                    "imovel_area_territorial",
                    models.CharField(
                        max_length=20, verbose_name="Área Territorial (m²)"
                    ),
                ),
                (
                    "imovel_area_construida",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Área Construída (m²)"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total da Venda",
                    ),
                ),
                ("valor_extenso", models.TextField(verbose_name="Valor por Extenso")),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("a_vista", "À Vista"),
                            ("parcelado", "Parcelado"),
                            ("financiado", "Financiado"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data de Pagamento")),
                (
                    "conta_bancaria",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Conta Bancária para Transferência",
                    ),
                ),
                (
                    "quantidade_parcelas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantidade de Parcelas"
                    ),
                ),
                (
                    "datas_parcelas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Datas das Parcelas"
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(verbose_name="Data de Entrega do Imóvel"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("finalizado", "Finalizado"),
                            ("assinado", "Assinado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Compra e Venda de Imóvel Completo",
                "verbose_name_plural": "Contratos de Compra e Venda de Imóveis Completos",
                "ordering": ["-created_at"],
            },
        ),
    ]
