# Generated by Django 5.2.3 on 2025-07-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contratocompravendaimovel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoLocacaoResidencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "proprietario_nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "proprietario_estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "proprietario_nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "proprietario_profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("proprietario_rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "proprietario_cpf",
                    models.CharField(max_length=14, verbose_name="CPF"),
                ),
                (
                    "proprietario_rua",
                    models.CharField(max_length=200, verbose_name="Rua"),
                ),
                (
                    "proprietario_numero",
                    models.CharField(max_length=10, verbose_name="Número"),
                ),
                (
                    "proprietario_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "proprietario_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "proprietario_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "proprietario_conjuge_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_nacionalidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nacionalidade do Cônjuge",
                    ),
                ),
                (
                    "proprietario_conjuge_profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_rg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RG do Cônjuge"
                    ),
                ),
                (
                    "proprietario_conjuge_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Cônjuge"
                    ),
                ),
                (
                    "locatario_nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "locatario_estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "locatario_nacionalidade",
                    models.CharField(
                        default="Brasileira",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "locatario_profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("locatario_rg", models.CharField(max_length=20, verbose_name="RG")),
                ("locatario_cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("locatario_rua", models.CharField(max_length=200, verbose_name="Rua")),
                (
                    "locatario_numero",
                    models.CharField(max_length=10, verbose_name="Número"),
                ),
                (
                    "locatario_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "locatario_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "locatario_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "locatario_conjuge_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Cônjuge"
                    ),
                ),
                (
                    "locatario_conjuge_nacionalidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nacionalidade do Cônjuge",
                    ),
                ),
                (
                    "locatario_conjuge_profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão do Cônjuge"
                    ),
                ),
                (
                    "locatario_conjuge_rg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RG do Cônjuge"
                    ),
                ),
                (
                    "locatario_conjuge_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Cônjuge"
                    ),
                ),
                (
                    "imovel_tipo",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("chacara", "Chácara"),
                            ("cobertura", "Cobertura"),
                            ("duplex", "Duplex"),
                            ("fazenda", "Fazenda"),
                            ("flat", "Flat"),
                            ("galpao", "Galpão"),
                            ("kitnet", "Kitnet"),
                            ("loft", "Loft"),
                            ("mansao", "Mansão"),
                            ("sitio", "Sítio"),
                            ("sobrado", "Sobrado"),
                            ("studio", "Studio"),
                            ("terreno", "Terreno"),
                        ],
                        max_length=20,
                        verbose_name="Tipo do Imóvel",
                    ),
                ),
                ("imovel_rua", models.CharField(max_length=200, verbose_name="Rua")),
                (
                    "imovel_numero",
                    models.CharField(max_length=10, verbose_name="Número"),
                ),
                (
                    "imovel_bairro",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "imovel_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "imovel_estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "imovel_matricula",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número da Matrícula"
                    ),
                ),
                (
                    "imovel_cartorio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Cartório onde foi Registrado",
                    ),
                ),
                (
                    "imovel_iptu",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número do IPTU"
                    ),
                ),
                (
                    "imovel_conta_agua",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número da Conta de Água",
                    ),
                ),
                (
                    "imovel_conta_luz",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número da Conta de Luz"
                    ),
                ),
                (
                    "valor_aluguel",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor do Aluguel"
                    ),
                ),
                (
                    "valor_aluguel_extenso",
                    models.CharField(max_length=500, verbose_name="Valor por Extenso"),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("boleto", "Boleto"),
                            ("pix", "PIX"),
                            ("transferencia", "Transferência Bancária"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "dia_pagamento",
                    models.CharField(
                        choices=[
                            ("1", "Dia 1"),
                            ("2", "Dia 2"),
                            ("3", "Dia 3"),
                            ("4", "Dia 4"),
                            ("5", "Dia 5"),
                            ("6", "Dia 6"),
                            ("7", "Dia 7"),
                            ("8", "Dia 8"),
                            ("9", "Dia 9"),
                            ("10", "Dia 10"),
                            ("11", "Dia 11"),
                            ("12", "Dia 12"),
                            ("13", "Dia 13"),
                            ("14", "Dia 14"),
                            ("15", "Dia 15"),
                            ("16", "Dia 16"),
                            ("17", "Dia 17"),
                            ("18", "Dia 18"),
                            ("19", "Dia 19"),
                            ("20", "Dia 20"),
                            ("21", "Dia 21"),
                            ("22", "Dia 22"),
                            ("23", "Dia 23"),
                            ("24", "Dia 24"),
                            ("25", "Dia 25"),
                            ("26", "Dia 26"),
                            ("27", "Dia 27"),
                            ("28", "Dia 28"),
                            ("29", "Dia 29"),
                            ("30", "Dia 30"),
                            ("31", "Dia 31"),
                        ],
                        max_length=2,
                        verbose_name="Dia de Pagamento",
                    ),
                ),
                (
                    "conta_bancaria",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Conta Bancária para Transferência",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(verbose_name="Data de Início da Locação"),
                ),
                (
                    "data_termino",
                    models.DateField(verbose_name="Data de Término da Locação"),
                ),
                (
                    "tipo_garantia",
                    models.CharField(
                        choices=[
                            ("caucao", "Caução"),
                            ("fiador", "Fiador/Avalista"),
                            ("seguro", "Seguro Fiança"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Garantia",
                    ),
                ),
                (
                    "valor_caucao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor da Caução",
                    ),
                ),
                (
                    "fiador_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Fiador"
                    ),
                ),
                (
                    "fiador_estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil do Fiador",
                    ),
                ),
                (
                    "fiador_nacionalidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nacionalidade do Fiador",
                    ),
                ),
                (
                    "fiador_profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão do Fiador"
                    ),
                ),
                (
                    "fiador_rg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RG do Fiador"
                    ),
                ),
                (
                    "fiador_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Fiador"
                    ),
                ),
                (
                    "fiador_rua",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Rua do Fiador"
                    ),
                ),
                (
                    "fiador_numero",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Número do Fiador"
                    ),
                ),
                (
                    "fiador_bairro",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bairro do Fiador"
                    ),
                ),
                (
                    "fiador_cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade do Fiador"
                    ),
                ),
                (
                    "fiador_estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado do Fiador",
                    ),
                ),
                (
                    "seguro_nome_seguradora",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome da Seguradora"
                    ),
                ),
                (
                    "seguro_prazo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Prazo do Seguro"
                    ),
                ),
                (
                    "seguro_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do Seguro",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Locação Residencial",
                "verbose_name_plural": "Contratos de Locação Residencial",
                "ordering": ["-created_at"],
            },
        ),
    ]
