# Generated by Django 5.2.3 on 2025-07-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_contratolocacaoresidencial"),
    ]

    operations = []
