# Generated by Django 5.2.3 on 2025-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_add_category_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Referência Externa"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="merchant_order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID da Ordem MP"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notification_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Dados da Notificação"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID do Pagamento MP"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="preference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID da Preferência MP",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Cartão de Crédito"),
                    ("debit_card", "Cartão de Débito"),
                    ("pix", "PIX"),
                    ("boleto", "Boleto"),
                    ("account_money", "Saldo no Mercado Pago"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Processando"),
                    ("approved", "Aprovado"),
                    ("cancelled", "Cancelado"),
                    ("failed", "Falhou"),
                    ("in_process", "Em Processo"),
                    ("in_mediation", "Em Mediação"),
                    ("rejected", "Rejeitado"),
                    ("refunded", "Reembolsado"),
                    ("charged_back", "Estornado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
